# NOTE: Be careful updating this file, as it is used by the setup script.
version: '3'
services:
  demo-api-server:
    build: .
    volumes:
      - ./:/code
      - /code/node_modules # Excludes node_modules
      - ./.firebase/emulators/:/opt/workspace:cached
      - ./.firebase/bin/:/root/.cache:cached
      - ./.firebase/config/:/root/.config:cached
      - ./.firebase/data/:/root/data
    ports:
      - "9229:9229"           # node-inspect debug port. Can be disabled if not being used.
      - "9900-9906:9900-9906" # expose for browser access
    environment:
      # Credentials URL
      - GCLOUD_PROJECT=dereekb-components
    command: npx nx run demo-api:serve
    tty: true
    networks:
      - demo-api-network

networks:
  demo-api-network:
    driver: bridge