version: '3'
services:
  demo-api-server:
    build: .
    volumes:
      - ./:/code
      - /code/node_modules  # Excludes node_modules
      - ./.cache:/root/.cache # Cache for firebase emulators
    ports:
      - "9229:9229"
      - "9990-9905"
    environment:
      # Credentials URL
      - GOOGLE_APPLICATION_CREDENTIALS=/code/service_account.json
      - GCLOUD_PROJECT=dereekb-components
