version: '3'
services:
  demo-api-server:
    build: .
    volumes:
      - ./:/code
      - /code/node_modules  # Excludes node_modules
    ports:
      - "9229:9229"
      - "9900-9905:9900-9905"
    environment:
      # Credentials URL
      - GOOGLE_APPLICATION_CREDENTIALS="path/to/key.json"
