version: 2.1 # use CircleCI 2.1

# YAML trick
defaults: &defaults
  working_directory: ~/code # "code" is our working directory
  resource_class: medium+
  docker:
    - image: cimg/node:16.13

# https://circleci.com/blog/config-best-practices-dependency-caching/

orbs:
  nx: nrwl/nx@1.1.3
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
            - node-cache-
      # install dependencies
      - run:
          name: install dependencies
          command: npm install
      # save any changes to the cache
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # initialize nx
      - nx/set-shas
      # build content
      - run: npx nx affected --base=$NX_BASE --target=build --parallel --max-parallel=2 --exclude=dbx-form # TODO: unexclude dbx-form later.
      # persist builds to workspace
      - persist_to_workspace:
          root: ~/code
          paths:
            - node_modules
            - dist
  test-with-node:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/code
      - run:
          name: run util tests
          command: npx nx test util
      - run:
          name: run rxjs tests
          command: npx nx test rxjs
      - run:
          name: run date tests
          command: npx nx test date
      - run:
          name: run dbx-core tests
          command: npx nx test dbx-core
      - run:
          name: run dbx-web tests
          command: npx nx test dbx-web
      - store_test_results:
          path: ~/code/.reports/jest/
  test-with-node-firebase:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/code
      - run: sudo apt-get update -y && sudo apt-get install -y curl openjdk-11-jre-headless
      - restore_cache:
          key: firebase-cache-
      - run:
          name: run firebase tests
          command: npx firebase emulators:exec --only auth,firestore,storage 'npx nx run-tests firebase'
      - run:
          name: run dbx-firebase tests
          command: npx firebase emulators:exec --only auth,firestore,storage 'npx nx run-tests dbx-firebase'
      - save_cache:
          key: firebase-cache-
          paths:
            - ~/.cache/firebase/emulators
      - store_test_results:
          path: ~/code/.reports/jest/
  publish-to-npm:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/code
      - run: echo pushing to npm
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-with-node:
          requires:
            - build
      - test-with-node-firebase:
          requires:
            - build
